name: character_generator
description: "Генератор персонажей для настольных игр"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.3
  uuid: ^4.4.0
  path_provider: ^2.1.1
  share_plus: ^9.0.0
  image: ^4.1.4
  path: ^1.8.3
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/classes/
    - assets/images/icons/
    - assets/images/
    
  generate: true